apiVersion: v1
kind: Service

metadata:
  name: fastapi-devops-service

spec:
  type: NodePort

  selector:
    app: fastapi-devops-app

  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000
      nodePort: 30080